const majorList = [
    { label: "Aerospace Engineering", value: "aerospace engineering" },
    { label: "Bioengineering", value: "bioengineering" },
    { label: "Chemical Engineering", value: "chemical engineering" },
    { label: "Civil Engineering", value: "civil engineering" },
    { label: "Computer Engineering", value: "computer engineering" },
    {
      label: "Computer Science and Engineering",
      value: "computer science and engineering",
    },
    { label: "Electrical Engineering", value: "electrical engineering" },
    { label: "Materials Engineering", value: "materials engineering" },
    { label: "Mechanical Engineering", value: "mechanical engineering" },
    { label: "African American Studies", value: "african american studies" },
    {
      label: "African and Middle Eastern Studies",
      value: "african and middle eastern studies",
    },
    { label: "American Indian Studies", value: "american indian studies" },
    {
      label: "American Literature and Culture",
      value: "american literature and culture",
    },
    {
      label: "Ancient Near East and Egyptology",
      value: "ancient near east and egyptology",
    },
    { label: "Anthropology (B.A.)", value: "anthropology (b.a)" },
    { label: "Anthropology (B.S.)", value: "anthropology (b.s)" },
    { label: "Asian American Studies", value: "asian american studies" },
    { label: "Arabic", value: "arabic" },
    { label: "Art History", value: "art history" },
    { label: "Asian Humanities", value: "asian humanities" },
    {
      label: "Asian Languages and Linguistics",
      value: "asian languages and linguistics",
    },
    { label: "Asian Religions", value: "asian religions" },
    { label: "Asian Studies", value: "asian studies" },
    { label: "Astrophysics", value: "astrophysics" },
    {
      label: "Atmospheric and Oceanic Sciences",
      value: "atmospheric and oceanic sciences",
    },
    {
      label: "Atmospheric and Oceanic Sciences/Mathematics",
      value: "atmospheric and oceanic sciences/mathematics",
    },
    { label: "Biochemistry", value: "biochemistry" },
    { label: "Biology", value: "biology" },
    { label: "Biophysics", value: "biophysics" },
    { label: "Business Economics", value: "business economics" },
    {
      label: "Central and East European Languages and Cultures",
      value: "central and east european languages and cultures",
    },
    { label: "Chemistry", value: "chemistry" },
    { label: "Chemistry/Materials Science", value: "chemistry/materials" },
    {
      label: "Chicana and Chicano Studies",
      value: "chicana and chicanos studies",
    },
    { label: "Chinese", value: "chinese" },
    { label: "Classical Civilization", value: "classical civilization" },
    { label: "Climate Science", value: "climate science" },
    { label: "Cognitive Science", value: "cognitive science" },
    { label: "Communication", value: "communication" },
    { label: "Comparative Literature", value: "comparative literature" },
    {
      label: "Computational and Systems Biology",
      value: "computational and systems biology",
    },
    { label: "Data Theory", value: "data theory" },
    { label: "Disability Studies", value: "disability studies" },
    {
      label: "Earth and Environmental Science",
      value: "earth and environmental science",
    },
    {
      label: "Ecology, Behavior, and Evolution",
      value: "ecology, behavior, and evolution",
    },
    { label: "Economics", value: "economics" },
    { label: "English", value: "english" },
    { label: "Environmental Science", value: "environmental science" },
    {
      label: "European Languages and Transcultural Studies",
      value: "european languages and transcultural studies",
    },
    {
      label:
        "European Languages and Transcultural Studies with French and Francophone",
      value:
        "european languages and transcultural studies with french and francophone",
    },
    {
      label: "European Languages and Transcultural Studies with German",
      value: "european languages and transcultural studies with german",
    },
    {
      label: "European Languages and Transcultural Studies with Italian",
      value: "european languages and transcultural studies with italian",
    },
    {
      label: "European Languages and Transcultural Studies with Scandinavian",
      value: "european languages and transcultural studies with scandinavian",
    },
    { label: "European Studies", value: "european studies" },
    { label: "Gender Studies", value: "gender studies" },
    { label: "Geography", value: "geography" },
    {
      label: "Geography/Environmental Studies",
      value: "geography/environmental studies",
    },
    { label: "Geology", value: "geology" },
    {
      label: "Geology/Engineering Geology",
      value: "geology/engineering geology",
    },
    { label: "Geophysics", value: "geophysics" },
    { label: "Global Studies", value: "global studies" },
    { label: "Greek", value: "greek" },
    { label: "Greek and Latin", value: "greek and latin" },
    { label: "History", value: "history" },
    {
      label: "Human Biology and Society (B.A.)",
      value: "human biology and society (b.a.)",
    },
    {
      label: "Human Biology and Society (B.S.)",
      value: "human biology and society (b.s.)",
    },
    {
      label: "International Development Studies",
      value: "international development studies",
    },
    { label: "Iranian Studies", value: "iranian studies" },
    { label: "Japanese", value: "japanese" },
    { label: "Jewish Studies", value: "jewish studies" },
    { label: "Korean", value: "korean" },
    { label: "Labor Studies", value: "labor studies" },
    { label: "Latin", value: "latin" },
    { label: "Latin American Studies", value: "latin american studies" },
    { label: "Linguistics", value: "linguistics" },
    {
      label: "Linguistics and Anthropology",
      value: "linguistics and anthropology",
    },
    {
      label: "Linguistics and Asian Languages and Cultures",
      value: "linguistics and asian languages and cultures",
    },
    {
      label: "Linguistics and Computer Science",
      value: "linguistics and computer science",
    },
    { label: "Linguistics and English", value: "linguistics and english" },
    { label: "Linguistics and Philosophy", value: "linguistics and philosophy" },
    { label: "Linguistics and Psychology", value: "linguistics and psychology" },
    { label: "Linguistics and Spanish", value: "linguistics and spanish" },
    { label: "Linguistics, Applied", value: "linguistics, applied" },
    { label: "Marine Biology", value: "marine biology" },
    { label: "Mathematics", value: "mathematics" },
    { label: "Mathematics, Applied", value: "mathematics, applied" },
    {
      label: "Mathematics/Applied Science",
      value: "mathematics/applied science",
    },
    { label: "Mathematics/Economics", value: "mathematics/economics" },
    {
      label: "Mathematics, Financial Actuarial",
      value: "mathematics, financial actuarial",
    },
  
    { label: "Mathematics for Teaching", value: "mathematics for teaching" },
    { label: "Mathematics of Computation", value: "mathematics of computation" },
    {
      label: "Microbiology, Immunology, and Molecular Genetics",
      value: "microbiology, immunology, and molecular genetics",
    },
    { label: "Middle Eastern Studies", value: "middle eastern studies" },
    {
      label: "Molecular, Cell, and Developmental Biology",
      value: "molecular, cell, and developmental biology",
    },
    { label: "Neuroscience", value: "neuroscience" },
    { label: "Nordic Studies", value: "nordic studies" },
    { label: "Philosophy", value: "philosophy" },
    { label: "Physics (B.A.)", value: "physics (b.a.)" },
    { label: "Physics (B.S.)", value: "physics (b.s.)" },
    { label: "Physiological Science", value: "physiological science" },
    { label: "Political Science", value: "political science" },
    {
      label: "Portuguese and Brazilian Studies",
      value: "portuguese and brazilian studies",
    },
    { label: "Psychobiology", value: "psychobiology" },
    { label: "Psychology", value: "psychology" },
    { label: "Religion, Study of", value: "religion, study of" },
    {
      label: "Russian Language and Literature",
      value: "russian language and literature",
    },
    { label: "Russian Studies", value: "russian studies" },
    { label: "Sociology", value: "sociology" },
    { label: "Southeast Asian Studies", value: "southeast asian studies" },
    { label: "Spanish", value: "spanish" },
    {
      label: "Spanish and Community and Culture",
      value: "spanish and community and culture",
    },
    { label: "Spanish and Linguistics", value: "spanish and linguistics" },
    { label: "Spanish and Portuguese", value: "spanish and portuguese" },
    {
      label: "Statistics and Data Science",
      value: "statistics and data science",
    },
    {
      label: "Individual Field of Concentration (B.A./ B.S.)",
      value: "individual field of concentration (b.a./ b.s.)",
    },
    { label: "Undeclared Humanities", value: "undeclared humanities" },
    { label: "Undeclared Life Sciences", value: "undeclared life sciences" },
    {
      label: "Undeclared Physical Sciences",
      value: "undeclared physical sciences",
    },
    { label: "Undeclared Social Sciences", value: "undeclared social sciences" },
    { label: "Architectural Studies", value: "architectural studies" },
    { label: "Art", value: "art" },
    { label: "Dance", value: "dance" },
    { label: "Design | Media Arts", value: "design | media arts" },
    { label: "World Arts and Cultures", value: "world acts and cultures" },
    {
      label: "Individual Field of Concentration in the Arts and Architecture",
      value: "individual field of concentratoin in the arts and architecture",
    },
    { label: "Ethnomusicology", value: "ethnomusicology" },
    { label: "Global Jazz Studies", value: "global jazz studies" },
    { label: "Music Composition", value: "music composition" },
    { label: "Music Education", value: "music education" },
    { label: "Music Industry", value: "music industry" },
    { label: "Music Performance", value: "music performance" },
    { label: "Nursing-Prelicensure", value: "nursing-prelicensure" },
    { label: "Public Affairs", value: "public affairs" },
    { label: "Film and Telivision", value: "film and telivision" },
    { label: "Theater", value: "theater" },
    {
      label: "Individual Field of Concentration in Theater, Film and Telivision",
      value: "individual field of concentration in theater, film and telivision",
    },
    {
      label: "Education and Social Transformation",
      value: "education and social transformation",
    },
    { label: "Public Health (B.A.)", value: "public health (b.a.)" },
    { label: "Public Health (B.S.)", value: "public health (b.s.)" },
  ];
  
  const sortedMajorsList = majorList.sort((a, b) => {
    return a.label.localeCompare(b.label);
  });
  
  export default sortedMajorsList;
  